//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautySystemDBEntities : DbContext
    {
        public BeautySystemDBEntities()
            : base("name=BeautySystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<PaymentForm> PaymentForm { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceForm> ServiceForm { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<Spa> Spa { get; set; }
        public virtual DbSet<SpaService> SpaService { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
