//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string OrderDetailID { get; set; }
        public string OrderID { get; set; }
        public string SpaServiceID { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public string ServiceFormID { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string EmpIDRequest { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual ServiceForm ServiceForm { get; set; }
        public virtual SpaService SpaService { get; set; }
    }
}
