//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SpaService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpaService()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
        [DisplayName("Spa Service Name")]
        public string SpaServiceID { get; set; }
        [DisplayName("Service Name")]
        public string ServiceID { get; set; }
        public string SpaID { get; set; }
        public string Description { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> DiscountMoney { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<int> Response { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Service Service { get; set; }
        public virtual Spa Spa { get; set; }
    }
}
